### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BlackHawk94** [OlympicCode/vHackOSBot-Python#2]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main = run(ut)
  File "main.py", line 7, in __init__
    network.attackTarget()
  File "/home/cabox/workspace/network.py", line 34, in attackTarget
    for targetNetwork in self.getListNetwork("cm"):
  File "/home/cabox/workspace/network.py", line 13, in getListNetwork
    return self.network["cm"]
KeyError: 'cm'

**Comment by vBlackOut** [comment]
weird, please connect on discord

**Comment by vBlackOut** [comment]
resolved  error
