### ISSUE TITLE
AttributeError: 'Utils' object has no attribute 'Configuration'

### ISSUE THREAD

**Issue by 0n1cOn3** [OlympicCode/vHackOSBot-Python#20]
I have installed everything correctly on macOS 10.13.4, with Python 2.7 & Python 3.6.

Heres the Log:

Traceback (most recent call last):
  File "/Users/0n1cOn3/Documents/vHackOSBot-Python-master/utils.py", line 176, in readConfiguration
    Configuration = yaml.load(stream, Loader=yaml.RoundTripLoader)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 83, in get_single_node
    event.start_mark)
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "config.yml", line 1, column 1
but found another document
  in "config.yml", line 2, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    ut = Utils()
  File "/Users/0n1cOn3/Documents/vHackOSBot-Python-master/utils.py", line 127, in __init__
    self.Configuration = self.readConfiguration()
  File "/Users/0n1cOn3/Documents/vHackOSBot-Python-master/utils.py", line 178, in readConfiguration
    self.viewsPrint("ErrorConfiguration", "{} [{}]".format("Error in your config.yml please check in", exc))
  File "/Users/0n1cOn3/Documents/vHackOSBot-Python-master/utils.py", line 187, in viewsPrint
    if condition in self.Configuration["show_info"] or "All" in self.Configuration["show_info"]:
AttributeError: 'Utils' object has no attribute 'Configuration'

**Comment by vBlackOut** [comment]
Please send me you config.yml ... Delete your username and password or replace per other information for better look error

**Comment by vBlackOut** [comment]
it's ok for you ?

**Comment by 0n1cOn3** [comment]
So i have to put the uID there instead my Login Credetials ? If yes, i must find out, where the uID is.

**Comment by 0n1cOn3** [comment]
i didnt make any other modification in the conf file.

The uID & Accesstoken did I delete it. Same Error...

**Comment by 0n1cOn3** [comment]
![image](https://user-images.githubusercontent.com/27576311/39849275-d0283b3c-540b-11e8-94ab-4e81785e9fff.png)

**Comment by 0n1cOn3** [comment]
![image](https://user-images.githubusercontent.com/27576311/39849318-0a76cbaa-540c-11e8-83ce-c1bfa53e27fe.png)

**Comment by 0n1cOn3** [comment]
btw: Exemple is written wrong 🤔 Its "Example" 😄

**Comment by vBlackOut** [comment]
yes delete space for left username and password

**Comment by vBlackOut** [comment]
username: (one_space_and_username)
password: (one_space_and_password)
