### ISSUE TITLE
Unable to run main.py

### ISSUE THREAD

**Issue by foster82** [OlympicCode/vHackOSBot-Python#26]
Hi all,

when i try to run python main.py i get this error.

/vHackOSBot-Python $ python2.7 main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from update import Update
  File "/home/jonathan/vhackos/vHackOSBot-Python/update.py", line 1, in <module>
    from utils import Utils
  File "/home/jonathan/vhackos/vHackOSBot-Python/utils.py", line 14, in <module>
    import ruamel.yaml as yaml
ImportError: No module named ruamel.yaml

I have run pip install -r requirments.txt and that all installed ok. I have tried it with python3 and python2.7. 

Any help would be greatly appreciated. 

Thanks

**Comment by cptcepk** [comment]
Re install python with all the aditionals options
