### ISSUE TITLE
"Transactions" error

### ISSUE THREAD

**Issue by 3HL** [OlympicCode/vHackOSBot-Python#8]
The script not run

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    main = run(ut)
  File "main.py", line 14, in __init__
    network = Network(ut)
  File "/home/vHackOSBot-Python/network.py", line 10, in __init__
    self.attackTarget(self.Configuration["attack_mode"])
  File "/home/vHackOSBot-Python/network.py", line 68, in attackTarget
    for info in yourbank["transactions"]:
KeyError: 'transactions'

**Comment by Suburbanno** [comment]
is outdated, please use Java bot.
